### ISSUE TITLE
Support for USB

### ISSUE THREAD

**Issue by lando07** [teddywlq/smifb2#2]
Hey I have a usb display adapter which has the SoC in this driver, but because it is usb, I can't use it. Is there possibly any way I could convert this to a USB driver? I don't know much about c, but I can tell everything is there.

**Comment by teddywlq** [comment]
This is PCIe interface driver. SM768 also can work as a USB display adapter for docking statation purpose. We have USB display driver. You can contact with your vendor to get it.

**Comment by happygaijin** [comment]
I am in this same situation. The only driver that they direct me to is the [Silicon Motion drivers](https://www.siliconmotion.com/downloads/index.html) for Windows and MacOS. Nothing for Linux. Can you point me toward the Linux USB display driver?

**Comment by teddywlq** [comment]
@papag00se You can contact with your vendor to get it.. The latest driver version is v2.10.1
